require('core.plugin_config.colorscheme')
require('core.plugin_config.conform')
require('core.plugin_config.cmp')
--require('core.plugin_config.fzf')
require('core.plugin_config.gitsigns')
--require('core.plugin_config.copilot')
require('core.plugin_config.lspconfig')
--require('core.plugin_config.lualine')
--require('core.plugin_config.nvim_ufo')
--require('core.plugin_config.peek')

require('core.plugin_config.indent-blankline')
require('core.plugin_config.neo-tree')
require('core.plugin_config.nvim-window-picker')
require('core.plugin_config.snippy')
require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
